AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Award FastAPI Moisture Classifier + Hybrid GPR

Globals:
  Function:
    Timeout: 60
    MemorySize: 1536

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - bedrock:InvokeModel
            Resource: '*'
        - Statement:
            Effect: Allow
            Action:
              - s3:PutObject
            Resource: '*'
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region
          BEDROCK_STRICT: "1"
      Events:
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: API endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
